baseurl = "//disconnected.systems"
title = "Disconnected Systems"
languageCode = "en-gb"

pygmentsStyle = "monokai"
pygmentsUseClasses = true
PygmentsCodeFences = true

googleAnalytics = "UA-57006875-2"

disqusShortname = "disconsys"
